// 1 pod with 1 container 
apiVersion: v1
kind: Pod
metadata:
  name: flipkart
spec:
  containers:
    - name: signup
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo signup; sleep 2 ; done"]
